added rollback mechanism
* added rollback mechanism

* some fixes

* making workflows status available in main branch too

diff --git a/.github/workflows/merge_and_migrate.yml b/.github/workflows/merge_and_migrate.yml
--- a/.github/workflows/merge_and_migrate.yml
+++ b/.github/workflows/merge_and_migrate.yml
@@ -1,15 +1,13 @@
 name: Migrate to Target
 
 on:
-  pull_request:
-    types:
-      - closed
+  push:
     branches:
       - main
     paths-ignore:
-      - "README.md"
-      - "Contributing.md"
-      - ".github/**"
+      - README.md
+      - Contributing.md
+      - .github/**
   workflow_dispatch:
     inputs:
       branch:
@@ -21,7 +19,6 @@ jobs:
   migrate_to_target:
     name: Migration to Target
     runs-on: ubuntu-latest
-    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
     env:
       SOURCE_HOST_URL: ${{ secrets.SOURCE_HOST_URL }}
       SOURCE_TOKEN: ${{ secrets.SOURCE_TOKEN }}
@@ -32,7 +29,7 @@ jobs:
       - name: Check out code
         uses: actions/checkout@v4
         with:
-          ref: ${{ github.event.inputs.branch || github.event.pull_request.base.ref }}
+          ref: ${{ github.event.inputs.branch || 'main' }}
 
       - name: Install dependencies
         run: |
@@ -50,7 +47,7 @@ jobs:
             VERSION=$(echo $LATEST_RELEASE | sed 's/^v//')
             
             if ! pipx install https://github.com/instabase/aihub-apps-ci-cd-workflows/releases/download/${LATEST_RELEASE}/cicd_aihub-${VERSION}-py3-none-any.whl; then
-              echo "Failed to install from GitHub release after failing to find local .whl file. Aborting."
+              echo "Failed to install from GitHub release. Aborting."
               exit 1
             fi
           fi
@@ -68,36 +65,67 @@ jobs:
             exit 1
           fi
 
-      - name: Migrate app to Target
+      - name: Create or Upload Project
+        id: create_project_step
         run: |
           IS_ADVANCED=$(jq -r '.source.is_advanced' config.json)
           SB_NAME=$(jq -r '.source.sb_name' config.json)
           FLOW_PATH=$(jq -r '.source.flow_path' config.json)
-          DEPLOYMENT_ID=$(jq -r '.source.deployment_id' config.json)
           DEPENDENCIES=$(jq -r '.source.dependencies' config.json)
-          REBUILD=$(jq -r '.settings.rebuild' config.json)
-
-          DEPLOY_FLAG=""
-          if [ -n "$DEPLOYMENT_ID" ] && [ "$DEPLOYMENT_ID" != "null" ]; then
-            DEPLOY_FLAG="--create_deployment"
-          fi
-
           DEPS_FLAG=""
           if [ -n "$DEPENDENCIES" ] && [ "$DEPENDENCIES" != "null" ]; then
             DEPS_FLAG="--upload_dependencies"
           fi
-
+          REBUILD=$(jq -r '.settings.rebuild' config.json)
           REBUILD_FLAG=""
           if [ "$REBUILD" = "true" ]; then
             REBUILD_FLAG="--rebuild"
           fi
-
           if [ "$IS_ADVANCED" = "true" ] && [ -n "$FLOW_PATH" ] && [ "$FLOW_PATH" != "null" ]; then
-            promote-solution --promote_solution_to_target --publish_advanced_app $DEPLOY_FLAG $DEPS_FLAG
+            promote-solution --promote_solution_to_target $DEPS_FLAG
           elif [ "$IS_ADVANCED" = "true" ] && [ -n "$SB_NAME" ] && [ "$SB_NAME" != "null" ]; then
-            promote-sb-solution --promote_solution_to_target --publish_advanced_app $DEPLOY_FLAG $DEPS_FLAG
+            promote-sb-solution --promote_solution_to_target $DEPS_FLAG
           else
-            promote-build-solution --publish_build_app $DEPLOY_FLAG $REBUILD_FLAG
+            promote-build-solution --create_build_project $REBUILD_FLAG
+          fi
+
+          PROJECT_ID=$(jq -r '.target.project_id' config.json)
+          echo "PROJECT_ID=$PROJECT_ID" >> $GITHUB_ENV
+          echo "Extracted Project ID: $PROJECT_ID"
+
+      - name: Create App
+        id: create_app_step
+        run: |
+          IS_ADVANCED=$(jq -r '.source.is_advanced' config.json)
+          SB_NAME=$(jq -r '.source.sb_name' config.json)
+          FLOW_PATH=$(jq -r '.source.flow_path' config.json)
+          REBUILD=$(jq -r '.settings.rebuild' config.json)
+          REBUILD_FLAG=""
+          if [ "$REBUILD" = "true" ]; then
+            REBUILD_FLAG="--rebuild"
+          fi
+          if [ "$IS_ADVANCED" = "true" ] && [ -n "$FLOW_PATH" ] && [ "$FLOW_PATH" != "null" ]; then
+            promote-solution --publish_advanced_app  
+          elif [ "$IS_ADVANCED" = "true" ] && [ -n "$SB_NAME" ] && [ "$SB_NAME" != "null" ]; then
+            promote-sb-solution --publish_advanced_app
+          else
+            promote-build-solution --publish_build_app $REBUILD_FLAG
+          fi
+
+      - name: Create Deployment
+        id: create_deployment_step
+        run: |
+          DEPLOYMENT_ID=$(jq -r '.source.deployment_id' config.json)
+          DEPLOY_FLAG=""
+          if [ -n "$DEPLOYMENT_ID" ] && [ "$DEPLOYMENT_ID" != "null" ]; then
+            DEPLOY_FLAG="--create_deployment"
+          fi
+          if [ "$IS_ADVANCED" = "true" ] && [ -n "$FLOW_PATH" ] && [ "$FLOW_PATH" != "null" ]; then
+            promote-solution $DEPLOY_FLAG
+          elif [ "$IS_ADVANCED" = "true" ] && [ -n "$SB_NAME" ] && [ "$SB_NAME" != "null" ]; then
+            promote-sb-solution $DEPLOY_FLAG
+          else
+            promote-build-solution $DEPLOY_FLAG
           fi
 
       - name: Create or Update Tag for Release
@@ -108,3 +136,30 @@ jobs:
           APP_RELEASE_VERSION=$(jq -r '.version' app_details.json)
           git tag -f -a "v${APP_RELEASE_VERSION}" -m "Release version ${APP_RELEASE_VERSION}"
           git push origin "v${APP_RELEASE_VERSION}" --force
+
+      - name: Rollback to Previous Version
+        if: failure() && steps.create_app_step.outcome == 'failure'
+        run: |
+          git fetch --tags
+          LATEST_TAG=$(git tag --sort=-v:refname | head -n 1)
+          echo "Latest tag found: $LATEST_TAG"
+      
+          if [ -z "$LATEST_TAG" ]; then
+              echo "No previous version found. Deleting build..."
+              promote-build-solution --delete_build
+              exit 1
+          fi
+      
+          echo "Reverting to previous version: $LATEST_TAG"
+          git reset --hard "$LATEST_TAG"
+          git clean -fd  
+      
+          REBUILD=$(jq -r '.settings.rebuild // "false"' config.json)
+          REBUILD_FLAG=""
+          if [ "$REBUILD" = "true" ]; then
+            REBUILD_FLAG="--rebuild"
+          fi
+      
+          jq --arg project_id "$PROJECT_ID" '.target.project_id = $project_id' config.json > config_updated.json && mv config_updated.json config.json
+          promote-build-solution --create_build_project $REBUILD_FLAG
+        
